### ISSUE TITLE
er staat onderaan nog copyright test

### ISSUE THREAD

**Issue by roxannewyns** [libis/LIBIS-Omeka-v2#1]
![image](https://user-images.githubusercontent.com/3798589/30367118-9cca8786-986d-11e7-84a0-651f1bcd235f.png)

**Comment by JorisLambrechts** [comment]
fix https://github.com/libis/LIBIS-Omeka-v2/commit/07feba47bf2252c6356659b621244b712459171e 

Zal het later vandaag nog deployen als er niemand met de site bezig is.
